# Generated by Django 5.0 on 2024-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_idea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votings',
            field=models.ManyToManyField(to='main_site.idea'),
        ),
    ]
