# Generated by Django 4.2.8 on 2024-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='images/idea.jpg', upload_to='images/'),
        ),
    ]
