# Generated by Django 5.0 on 2024-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_alter_idea_description'),
        ('main_site', '0007_request'),
    ]

    operations = [
    ]
