# Generated by Django 5.0 on 2024-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_rename_abonent_request_user_to_remove_request_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
