# Generated by Django 5.0 on 2024-03-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_request_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='idea',
            field=models.ManyToManyField(default=1, to='main_site.idea'),
        ),
    ]
