# Generated by Django 5.0 on 2024-03-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_request_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='idea',
        ),
        migrations.AddField(
            model_name='request',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.idea'),
        ),
    ]
