# Generated by Django 5.0 on 2024-04-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_remove_request_idea_request_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_to',
        ),
    ]
